// OBRS-390 — the last line of defence before a prod bundle starts taking real money.
//
// WHY THIS EXISTS AT RUNTIME AND NOT ONLY IN THE BUILD SCRIPT
// `scripts/inject-prod-env.js` validates the values it *generates*, but it is not the
// only way `environment.prod.local.ts` can come into being: it is gitignored, so a
// hand-written or stale copy is reviewed by nobody and still builds cleanly. This
// check runs against the bundle that actually shipped, reading the values it actually
// holds — the one place where the config is no longer hypothetical.
//
// WHY REFUSING TO BOOT IS THE RIGHT FAILURE
// Every value checked here fails SILENTLY in prod. A `pkey_test_` key tokenizes
// against Omise's test vault, the payment call returns success, the ticket is issued,
// and no money moves — nothing in any log says so until somebody reconciles revenue
// weeks later. A blank page on the first prod smoke test is enormously cheaper.
// (Same reasoning as the backend's ProdReferenceDataGuard — OBRS-449.)
//
// WHY THE `production` KEY CANNOT DEFUSE THIS
// These checks only run when `production === true`, which would be a silent no-op if
// that flag could be lost. It cannot: `environment.prod.ts` hardcodes `production`,
// `useMockPayments` and `useDevApiEndpoints` as committed literals. Only the values
// that genuinely vary per deploy (apiUrl, omisePublicKey, promptpay id, …) come from
// `environment.prod.local.ts` — and those are exactly the ones asserted below.

export interface ProdCheckedConfig {
  production: boolean;
  apiUrl: string;
  omisePublicKey: string;
  useMockPayments: boolean;
  useDevApiEndpoints: boolean;
  promptpay: { id: string };
}

export class ProdConfigError extends Error {
  constructor(failures: string[]) {
    super(
      [
        'PROD CONFIG REJECTED — refusing to boot a production bundle that cannot take real money.',
        '',
        ...failures.map((f) => `  - ${f}`),
        '',
        'These values come from `src/environments/environment.prod.local.ts`, which is',
        'generated by `node scripts/inject-prod-env.js` from build-time env vars.',
        'See docs/prod/RUNBOOK-OBRS-390-prod-frontend-config.md.',
      ].join('\n'),
    );
    this.name = 'ProdConfigError';
  }
}

// The placeholder committed in environment.base.ts. Reaching prod with it means the
// PromptPay QR encodes an account that is not ours — customers pay, we do not get paid.
const BASE_PROMPTPAY_PLACEHOLDER = '0123456789';

/**
 * No-ops for every non-prod build. Call it unconditionally from main.ts; the
 * `production` flag is what selects prod, exactly like Spring's `@Profile("prod")`.
 */
export function assertProdConfig(env: ProdCheckedConfig): void {
  if (!env.production) {
    return;
  }

  const failures: string[] = [];

  // `startsWith('pkey_live_')` rather than `!startsWith('pkey_test_')` on purpose:
  // it also rejects an empty string, an unsubstituted placeholder, and a secret key
  // pasted in by mistake. A denylist only catches the one mistake we thought of.
  const key = String(env.omisePublicKey ?? '').trim();
  if (!key.startsWith('pkey_live_')) {
    failures.push(
      `omisePublicKey is not a live Omise public key (got ${describeKey(key)}) — ` +
        'card payments would tokenize against the test vault and no money would move.',
    );
  }

  if (env.useMockPayments !== false) {
    failures.push(
      'useMockPayments is not false — the card and QR flows would skip the payment ' +
        'gateway entirely and issue free tickets.',
    );
  }

  if (env.useDevApiEndpoints !== false) {
    failures.push(
      'useDevApiEndpoints is not false — OTP and OTP-login would call the /test ' +
        'endpoints, which only exist under the backend dev profile.',
    );
  }

  const apiUrl = String(env.apiUrl ?? '').trim();
  if (!apiUrl.startsWith('https://')) {
    failures.push(
      `apiUrl is not https (got '${apiUrl}') — a prod bundle left on the ` +
        'environment.base.ts localhost default reaches no backend at all.',
    );
  }

  const promptpayId = String(env.promptpay?.id ?? '').trim();
  if (!promptpayId || promptpayId === BASE_PROMPTPAY_PLACEHOLDER) {
    failures.push(
      `promptpay.id is still the environment.base.ts placeholder ('${promptpayId}') — ` +
        'the QR would encode an account that is not ours.',
    );
  }

  if (failures.length > 0) {
    throw new ProdConfigError(failures);
  }
}

// Never echo a full key back into a console a customer can open. The prefix is
// what makes the failure diagnosable; the rest is noise.
function describeKey(key: string): string {
  if (!key) {
    return 'an empty value';
  }
  const prefix = key.slice(0, 10);
  return `'${prefix}…', ${key.length} chars`;
}
